### ISSUE TITLE
Menu bar icon not visible

### ISSUE THREAD

**Issue by plam4u** [johnno1962/InjectionApp#19]
Hi there,

I've installed the standalone app and I wanted to test if the injection works but the icon that should appear in the menu bar from which I tap "Inject Source" doesn't appear at all.

Can I run the injection without the app being available in the menu bar? 
I've tried System Preferences > Keyboard > Shortcuts but it doesn't seem to work.

**Comment by johnno1962** [comment]
Odd, I can TeamViewer if you like please send the co-ords to injection at johnholdsworth.com

**Comment by johnno1962** [comment]
Did you run the App ?

**Comment by plam4u** [comment]
I did a workaround and now it works for me.

I created an Automator script and I execute this script:
/Applications/Injection.app/Contents/Resources/injectSource 

Then I added shortcut to the Service that I just created.

To answer your previous questions:
yes, I was running the app.

This will work for me for now. But when I have a timeslot, I would definitely like to have a call with you and resolve it and use the officially suggested way of working with the standalone app.

**Comment by johnno1962** [comment]
All I can thinnk of is there isn’t enough space on your menu bar as this hasn’t been reported before nor has anything changed. Let me know if you find out what the problem is (or not)

**Comment by plam4u** [comment]
Thank you, John. When I have updates on the menu bar issue, I'll update this thread.

**Comment by plam4u** [comment]
Hey John,

I've restarted my computer and now I see the icon together with the icons for Karabiner (see attached image). On the screenshot you can see that there are 2 square icons and the Injection App icons separated from the rest of the icons. They appear randomly on different position after restart of the computer. These icons for Karabiner usually disappear (I don't know when or why). But since the Injection icon is there, I'm sure it will disappear at some point as well. 

The issue with the menu bar started since I updated to OS X Sierra.

Edit: another observation is that the icons move to the left until they disappear. The movement is triggered by selecting a window on a different monitor. I have a 2 monitor setup and every time I focus something on the other monitor I see the icons move to the left towards ".... Window | Help" menu items.

![2017-03-09_19-16-22](https://cloud.githubusercontent.com/assets/500339/23764192/f47b4c54-04fc-11e7-946b-7f23521dd0f5.png)

**Comment by johnno1962** [comment]
Did you file a radar :)

**Comment by plam4u** [comment]
No, I've never have done anything like that - reporting issues. Actually, the first time I report anything is this library. I really care about it and I want to make sure that it works.

**Comment by plam4u** [comment]
Not sure if it's related but Injection is stuck. It keeps rebuilding a file that I haven't changed since the morning. I tried the method using Notification Center and I can detect the injection in the file that I actually work on.

Maybe it's related to a different thing. I have Xcode 7 and Xcode 8 for the project since I have to support some stuff that are old.

Should I create another issue? I've tried to search for a similar question in the other Open and Closed issues but I don't find information about that.

**Comment by johnno1962** [comment]
I can TeamViewer if you like please send the co-ords to injection at johnholdsworth.com

**Comment by plam4u** [comment]
Thank you John for the quick help.

SOLUTION:
The quick fix is to CMD+Drag the icon and stick it together with the other icons. 
Once done, the icons stop moving to the left till they disappear.

The issue still exists for OS X but at least we have a way to continue using our apps.

**Comment by plam4u** [comment]
John,

quick comment for the double-injection issue.

Things I've tried that do NOT work:
- restart the simulator
- restart Xcode
- restart Injection App
- delete Derived Data

What works is to reset the simulator, it stopped double-injecting.

EDIT: One more thing that I should add is that the injection notification INJECTION_BUNDLE_NOTIFICATION was executing the "-injected" method. It's possible that both the notification and the "-injected" were executed.

**Comment by johnno1962** [comment]
Ahhh, mystery solved ! -injected and the notification are separate.
