### ISSUE TITLE
Timeout waiting for connection from client app

### ISSUE THREAD

**Issue by sergioutama** [johnno1962/InjectionApp#2]
Hi John, first, thanks for making this app :)

I installed it and always received `Timeout waiting for connection from client app` error message whenever I do `Inject Source`

<img width="423" alt="screen shot 2016-12-28 at 12 40 35 pm" src="https://cloud.githubusercontent.com/assets/1159163/21514041/e0c97742-ccfa-11e6-8193-869e62452194.png">

Here is my configuration
Xcode 8.2.1 (8C1002)
MacOS Sierra 10.12.2 (16C67)

Ps: It seems Xcode 8.2.1 also unable to load the Injectionforxcode bundle

Is there any way for me to debug this error and contribute to the project?

**Comment by johnno1962** [comment]
Hi, the project is a bit of a difficult build as it needs clones of practically evevrythhing else I’ve written on github but I may post it before too long. In the mean time can you check the contents of the file /tmp/helper.log. It should contain something like:

bootstrapEntry: 0x106041a60
payloadBundle: 0x7ffc8a60be20
payloadPath: /Users/johnholdsworth/Library/Developer/Xcode/DerivedData/Injectorator-bmmwkbujuyhhrnclvfjewhmitvuf/Build/Products/Debug/Injection.app/Contents/Resources/InjectionLoader.bundle/InjectionLoader
pathBuff: 776 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/libexec/MobileGestaltHelper
dyldPath: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/libdyld.dylib
dlopen() offset: 0x1e69, dlerror() offset: 0x1d6d

**Comment by johnno1962** [comment]
I’ve uploaded the source but it’s a tricky build and where you having a problem will be difficult to debug. /tmp/helper.log is the place to look!

**Comment by sergioutama** [comment]
So not sure what happened but I removed previous installation and the helper, restart my Mac do the following :

- Download the latest app
- Install the helper
- Unsign Xcode
- Clean and Clean build folder
- Run my project using unisgned Xcode
- inject source from plugin
- Magic happen

I would like to find out what exactly happening with the plugin, will try it with my other machine.
Meanwhile I'll close the issue

Thanks @johnno1962
