### ISSUE TITLE
Problem injecting current tab or split window.

### ISSUE THREAD

**Issue by zenangst** [johnno1962/InjectionApp#22]
It seems like the injection scripts has a bit of trouble resolving which window split or tab that is active.
I find myself trying to inject code only to find that it either throws an error or nothing happening.
While investing this a bit it looks like the injection script (guessing the apple script resolving the current active document) returns the wrong document that is trying to inject.

It would be nice if it could be more precise when getting the document. With that said, it works like a charm and InjectionApp has grown to be a part of my core workflow at this point.

**Comment by johnno1962** [comment]
Hi Chris, yes failing to select the right file when you are using tabs or split view is the soft underbelly of Injection - or should I say was… I’ve uploaded a new version which selects the most recently modified file if there is any ambiguity. Would you like to download it and kick the tires?

**Comment by zenangst** [comment]
Out and about at the moment, I'll take it for a ride when I get home. I'll keep you posted 😎

**Comment by zenangst** [comment]
@johnno1962 Seems to be working as intended! This is amazing 🥂
