### ISSUE TITLE
Bundle Load Error when injecting from AppCode

### ISSUE THREAD

**Issue by lyahdav** [johnno1962/InjectionApp#23]
I am able to inject fine from Xcode, but I get the error below when patching from AppCode. I tried patching main.m too, but same error.
```
.../Logs/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle8.bundle/InjectionBundle, 265): Library not loaded: @rpath/XCTest.framework/XCTest
Referenced from: .../Logs/iOSInjectionProject/build/Debug-iphonesimulator/InjectionBundle8.bundle/InjectionBundle
Bundle Load Error
*** Bundle has failed to load. If this is due to symbols not found, this may be due to symbols being hidden from dynamic libraries. ***
```

Why would it look for `XCTest`?

**Comment by lyahdav** [comment]
Would be nice to have a fix but I'm working around this for now by running the app from Xcode, enabling File Watcher from the Injection menu, and then editing in AppCode.

**Comment by johnno1962** [comment]
Odd problem. What is the path to your Xcode?

**Comment by lyahdav** [comment]
Strangely enough I tried to reproduce today and couldn't. It works fine from AppCode now. Maybe a restart of AppCode or Xcode resolved it? My path to Xcode is `/Applications/Xcode.app`.
