### ISSUE TITLE
Global shortcut key doesn't work with Swedish keyboard layout

### ISSUE THREAD

**Issue by zenangst** [johnno1962/InjectionApp#24]
Ohai, it's me again.

I'm having issues with the global shortcut key (^=) on a Swedish keyboard layout.
Control + Shift + = does not do what it is suppose to, it just renders a default macOS beeping sound.
It would be absolutely ace if this was a configuration option that you could access from the menu bar.

**Comment by johnno1962** [comment]
Ola, you again!

Do you mean control-= not control-shift-= which would be control-+ or if this different in Sweeden? control-shift-= did something different in the old plugin ("inject and reset”)

**Comment by zenangst** [comment]
<kbd>shift</kbd> + <kbd>0</kbd> is equal to =

Where as 

<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>0</kbd> does nothing apparently :/

![img_0678](https://cloud.githubusercontent.com/assets/57446/24760888/34f09872-1aea-11e7-9957-4ca5aa4df22a.JPG)

**Comment by zenangst** [comment]
I think I just figure it out. I was just using the wrong key :)

The injection menu bar app tricked me, I'm suppose to use this key:
<img width="321" alt="screen shot 2017-04-06 at 17 20 36" src="https://cloud.githubusercontent.com/assets/57446/24762104/a147dbd6-1aed-11e7-939c-23945d569fa5.png">

**Comment by johnno1962** [comment]
Weird! The hotkey uses a very old Carbon api which could explain things.
