### ISSUE TITLE
Error: Could not open filemap

### ISSUE THREAD

**Issue by igortxito** [johnno1962/InjectionApp#25]
Hi.
Everytime I try to inject source I get this error.
After a lot of try I can't go further.
Thanks for your great work!

version: XCode 8.3.1
** Could not open filemap ‘/Users/[...]/Library/Developer/Xcode/DerivedData/CartaGin-ftrserdhowecsafpagutmyzoxnrl/Build/Intermediates/XXX.build/Debug-iphonesimulator/Cartasc**

**Comment by eligat** [comment]
I seem to have the same issue. More info from Injection Console:
`at .../Injection.app/Contents/Resources/common.pm line 61. 
main::error('Could not open filemap ×sers/eligat/Library/Develope...') called at .../Injection.app/Contents/Resources/injectSource.pl line 269`

**Comment by johnno1962** [comment]
Do you have spaces in your path to the project?

**Comment by eligat** [comment]
No, only latin letters, `_` and `-`

**Comment by johnno1962** [comment]
Odd.. can you send a complete copy of console window to injection at johnholdsworth.com please?

**Comment by eligat** [comment]
Sent email. Thanks for your work, btw)

**Comment by zenangst** [comment]
I seemed to have run into the same issue here. I had a space in the target name. I renamed it to use a dash instead of a space. Looks like that fixed it, but I'm unsure. @eligat maybe you could do the same to confirm or deny my hypothesis.

**Comment by zenangst** [comment]
@johnno1962 @eligat seems like I can reproduce this consistently. If the target name has a space in it, it will fail. If I switch that out to use a dash, it works.

`AppName Staging` doesn't work.
`AppName-Staging` works.

@johnno1962 you reckon this would be easy to handle in InjectionApp?

**Comment by johnno1962** [comment]
@zenangst, thanks for really boxing this in so I could replicate it. I’ve pushed a new version of the Injection App that seems to have this fixed to http://johnholdsworth.com/injection.html

**Comment by zenangst** [comment]
@johnno1962 My pleasure mate! I'll take it for a spin today, keep you posted! ❤️

**Comment by zenangst** [comment]
@johnno1962 everything seems good now with the new version 🚀

**Comment by johnno1962** [comment]
Excellent.

**Comment by Rnorback** [comment]
Love this app btw. And this thread solved my problem, thanks for the fix John!
