### ISSUE TITLE
Updating UIView

### ISSUE THREAD

**Issue by theklausster** [johnno1962/InjectionApp#37]
Hi John

Awesome framework
Anyway to update the simulator in a given UIView? 

It seems like it's updating the console, but there's no effect when changing the background color in the uiview on the simulator

Console is saying: 
62 injections performed so far.
> Injection: Ignore any warning, Swizzled UIViewName 0x126fddca0 -> 0x103487722

**Comment by johnno1962** [comment]
Is this the app store version? Is the view/view controller being redrawn?

**Comment by theklausster** [comment]
It’s the version for Xcode 9.3 downloaded from website.

I can hit the injection func in debug mode, but do I need to do additional steps to refresh the uiview?

**Comment by johnno1962** [comment]
I can’t really tell what you need to be doing from this end. The typical mistake people make is to inject the code but not force the refresh. For example changing the code to redraw but not calling it.

**Comment by theklausster** [comment]
Thanks John, you can close this one.

Den tor. 21. jun. 2018 kl. 14.02 skrev John Holdsworth <
notifications@github.com>:
