### ISSUE TITLE
.m file duplicate error

### ISSUE THREAD

**Issue by maksimpiriyev** [johnno1962/InjectionApp#38]
for the .m file changes it tries to compile but  does not update and prints in the console as 
"Loading .dylib - Ignore any duplicate class warning..."
also, it does not detect if the .cpp file is updated in case people use .c/.cpp projects with swift together

**Comment by maksimpiriyev** [comment]
note also that function i am trying is 
```void doit();``` in .h file

and in .m file
```
void doit(){
    printf("ahaa");
}
```

**Comment by johnno1962** [comment]
You can ignore the “Duplicate class warning” but I’m afraid you can’t inject C++!

**Comment by maksimpiriyev** [comment]
but it is in objective-c file inside .m file and the code is not updated

**Comment by maksimpiriyev** [comment]
the class variable methods inside objective-c get updated but strangely not the ordinary global methods/functions

**Comment by johnno1962** [comment]
You can only inject Objective-C or Swift methods, not global functions. They need to be dynamically dispatched.

**Comment by maksimpiriyev** [comment]
what do you mean "dynamically dispatched"?

**Comment by johnno1962** [comment]
You can google that and get the answer but from injection’s point of view you can only inject methods of Objective-C or Swift classes is what you need to know.

**Comment by maksimpiriyev** [comment]
what about c++ virtual methods ?

**Comment by maksimpiriyev** [comment]
if i use them inside .mm file

**Comment by johnno1962** [comment]
no

**Comment by maksimpiriyev** [comment]
I appreciate your feedback this tool is great
