### ISSUE TITLE
Shortcut won't work

### ISSUE THREAD

**Issue by rajderks** [johnno1962/InjectionApp#4]
After trying different shortcuts for the "Inject Source" service I can definitely say that the service-shortcut does not work on my machine.

I am running Mac OS Sierra 10.12.1
Xcode Version 8.2.1 (8C1002)

current shortcut: command + ctrl + `

*edit* ctrl + cmd + s works, but only when I have selected text in the same file.

**Comment by johnno1962** [comment]
I’ve been able to get shortcuts to work in Xcode but you need selected text as well so Injection can determine the current document.
