### ISSUE TITLE
Symbol not found _$SBOWV

### ISSUE THREAD

**Issue by thomasvalera** [johnno1962/InjectionApp#41]
Hi! I just installed Injection III via the App Store but can't seem to get it to work on both my own project as well as the GettingStarted project.

Setup:
* Xcode 10.2
* Injection III via AppStore
* Started Injection
* Added `Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle")!.load()` to `AppDelegate`
* Ran GettingStarted on multiple devices under which iPhone Xs Max & iPhone 8 (12.2)

Error:
```
Error loading /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10:  
dlopen(/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10, 265): Symbol not found: _$SBOWV

Referenced from: /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10
  
Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
 
in /Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle/iOSInjection10
```

I'm not sure what I'm doing wrong, the file `libswiftCore.dylib` is at the correct location, Xcode is updated, devices have been reset, laptop restarted etc..

Does anyone have a suggestion?

**Comment by johnno1962** [comment]
Hi, My bad there, I’ve updated [GettingStarted.zip](http://johnholdsworth.com/GettingStarted.zip) for Xcode 10.2. Could you try again please?
You need to change your bundle path to remove the "10" - that was for Xcode 10.1

**Comment by thomasvalera** [comment]
Great that was it, thanks a lot!
