### ISSUE TITLE
Build failed - Can't find method "print" on an undefined value

### ISSUE THREAD

**Issue by liamjdouglas** [johnno1962/InjectionApp#7]
When trying to inject I get

`Can’t call method “print” on an undefined value at /Applications/Injection.app/Contents/Resources/injectSource.pl line 254, <GEN2> chunk 1.`

Running on iOS project on macOS 10.12.2. Xcode 8.2.1, iPhone 7 simulator on 10.2, Perl v5.18.2.

**Comment by johnno1962** [comment]
Sorry, my bad there. There was a bug affecting large projects. Please download again and give it a try.

**Comment by liamjdouglas** [comment]
Working. Thanks for fixing so quickly.
